### ISSUE TITLE
Manage Datadog account

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#69]
Talk to customer rep and try to get a volume discount -- hopefully retroactive

**Comment by pdpinch** [comment]
@blarghmatey can you update this issue with our plan for datadog?

**Comment by blarghmatey** [comment]
The current plan that we are on is for 8 comitted hosts and hourly overages at $0.03/hr. In order to reduce our costs we are going to commit to 40 hosts at $15/host/month and monthly overages at $18/host/month. In order to make this plan retroactive for the month of March we will need to have a signed agreement in place by the end of the week (3/31).

The number of committed hosts is open for debate. We currently have 47 monitored hosts. That doesn't include any of the new logging infrastructure which is a total of 6 instances, but we will also be terminating the 4 old syslog instances.

@pdpinch If you think that we should go one direction or another with the number of committed hosts then I am happy to discuss. One thing to note is that if we go below the number of committed hosts then we will still be billed for them which is why we were thinking of committing to slightly fewer than the current number of instances.
